### ISSUE TITLE
Electrum multisig transactions with trezor bridge randomly fails with TransportException code 400: session not found

### ISSUE THREAD

**Issue by pingec** [trezor/trezord-go#197] opened 2020-10-25 19:12 UTC
Hello,

I initially opened this issue at https://github.com/spesmilo/electrum/issues/6684 but was told this is likely a bridge issue, so I am reporting it here as well.

I am trying to use:

- Trezor Model T firmware 2.3.4 (also tested with 2.3.3)
- Trezor Bridge Version: 2.0.27
- Electrum 4.0.4 Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)]. On platform: Windows-10-10.0.19041-SP0

When I try to sign a multisig transaction (usually they are large eg. 100-200 inputs) the signing will mostly fail with the following message:

```TransportException('trezord: release/10 failed with code 400: session not found')```

![image](https://user-images.githubusercontent.com/2735374/97062439-292f1e00-159b-11eb-90ba-b4de98860e68.png)

The trezor signing takes a long time (many minutes) and sometimes this error will show up almost immediately, sometimes it will show up after a while and sometimes there is no error and the signing actually succeeds. It fails about 80% of time.

Using webusb instead works just fine without any issues.

**Comment by prusnak** [comment] 2020-10-25 19:41
Are you using any other software that might communicate with Trezor while you are signing TX with Electrum? (such asBrowser with wallet.trezor.io or suite.trezor.io open, a Trezor Connect enabled wallet or Trezor Suite desktop app)

**Comment by pingec** [comment] 2020-10-26 08:59
I do not think so, none of the mentioned apps nor websites were open or running. I now tried again with my main browser closed and opening a browser I have never used for any crypto wallet operations and I opened only the bridge status page in it.

From the bridge status page I saw that the session status was "no session" until I started signing a transaction with electrum, at that point the session status changed to a number and finally when electrum showed that error again, the session was again showing "no session".

**Comment by prusnak** [comment] 2020-11-09 22:22
We are releasing bridge 2.0.30 soon - will you please test the binaries from https://wallet.trezor.io/data/bridge/2.0.30/index.html and let us know whether this helped?

**Comment by pingec** [comment] 2020-11-12 09:40
I have tested and I the issue is still there

**Comment by matejcik** [comment] 2022-05-25 13:55
this seems to be the same thing as https://github.com/trezor/trezor-suite/issues/3225

**Comment by prusnak** [comment] 2022-05-25 14:15
I am closing this as a duplicate of https://github.com/trezor/trezord-go/issues/247

Even though this issue is older the other one contains more useful information.

**Closed by prusnak** 2022-05-25 14:15 UTC
